name: Test

on:
# TODO: Uncomment when using
  # pull_request:
  #   types:
  #     - synchronize
  #     - opened
  #     - reopened
  #     - unlocked
  #   paths:
  #     - "src/backend/**"
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "src/backend/**"
  # workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node 22
        uses: actions/setup-node@v5
        with:
          node-version: "22.18.0"

      - uses: extractions/setup-just@v3

      - name: Install dependencies
        run: just deps

      - name: Run tests with coverage
        run: just test coverage
